import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import { Cuprum } from 'next/font/google';
import { Fira_Code } from "next/font/google"; // Note the underscore
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const cuprum = Cuprum({
//   subsets: ['latin'],
//   variable: '--font-cuprum', // This creates a CSS variable
// });
const firaCode = Fira_Code({
  subsets: ["latin"],
  variable: "--font-fira-code", // Define the CSS variable name
});
// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "OJ - Learn, Code and Practice",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" rel="stylesheet"/>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20,400,0,0&icon_names=check_circle" />
      </head>
      <body
        className={`${firaCode.variable} antialiased selection:bg-white selection:text-black `}
      >
         <Navbar /> 
        {children}
        <Footer/>
      </body>
    </html>
  );
}
